### ISSUE TITLE
Using a different AES key causes an unhandled exception

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#202]
If you restart Nevergreen with a different AES key any previously added trays with a passwords will cause an exception to be thrown.

**Comment by GentlemanHal** [comment]
```java
javax.crypto.BadPaddingException: Given final block not properly padded
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:991)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:847)
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
        at javax.crypto.Cipher.doFinal(Cipher.java:2165)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at nevergreen.crypto$decrypt.invokeStatic(crypto.clj:30)
        at nevergreen.crypto$decrypt.invoke(crypto.clj:28)
        at nevergreen.api.projects$fetch_tray.invokeStatic(projects.clj:55)
        at nevergreen.api.projects$fetch_tray.invoke(projects.clj:51)
        at nevergreen.api.projects$fetch_all.invokeStatic(projects.clj:65)
        at nevergreen.api.projects$fetch_all.invoke(projects.clj:64)
        at nevergreen.api.projects$get_all.invokeStatic(projects.clj:82)
        at nevergreen.api.projects$get_all.invoke(projects.clj:80)
        at nevergreen.api.routes$fn__6540.invokeStatic(routes.clj:22)
        at nevergreen.api.routes$fn__6540.invoke(routes.clj:22)
        at compojure.core$wrap_response$fn__1890.invoke(core.clj:158)
        at compojure.core$pre_init$fn__1941.invoke(core.clj:328)
        at nevergreen.wrap_convert_keys$wrap_convert_keys$fn__6379.invoke(wrap_convert_keys.clj:8)
        at nevergreen.wrap_redact_sensitive$wrap_restore_sensitive$fn__6407.invoke(wrap_redact_sensitive.clj:17)
        at ring_curl.middleware$wrap_curl_logging$fn__6494.invoke(middleware.clj:18)
        at nevergreen.wrap_redact_sensitive$wrap_redact_sensitive$fn__6403.invoke(wrap_redact_sensitive.clj:11)
        at ring.middleware.json$wrap_json_body$fn__6145.invoke(json.clj:44)
        at ring.middleware.json$wrap_json_response$fn__6170.invoke(json.clj:87)
        at nevergreen.wrap_cache_control$wrap_no_cache$fn__6179.invoke(wrap_cache_control.clj:16)
        at nevergreen.wrap_cors_headers$wrap_cors_headers$fn__6386.invoke(wrap_cors_headers.clj:9)
        at nevergreen.wrap_exceptions$wrap_exceptions$fn__6396.invoke(wrap_exceptions.clj:12)
        at ring.middleware.gzip$wrap_gzip$fn__6533.invoke(gzip.clj:94)
        at compojure.core$pre_init$fn__1943$fn__1946.invoke(core.clj:335)
        at compojure.core$wrap_route_middleware$fn__1874.invoke(core.clj:127)
        at compojure.core$wrap_route_info$fn__1879.invoke(core.clj:137)
        at compojure.core$wrap_route_matches$fn__1883.invoke(core.clj:146)
        at compojure.core$routing$fn__1898.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2693)
        at clojure.core$some.invoke(core.clj:2684)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at compojure.core$routes$fn__1902.invoke(core.clj:192)
        at compojure.core$wrap_routes$fn__1953.invoke(core.clj:348)
        at compojure.core$routing$fn__1898.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2693)
        at clojure.core$some.invoke(core.clj:2684)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at compojure.core$routes$fn__1902.invoke(core.clj:192)
        at ring.adapter.jetty$proxy_handler$fn__2067.invoke(jetty.clj:25)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by cowley05** [comment]
Ahh good catch, we probably need to delete the passwords in the config when we do this since you wont be able to decrypt them anymore?
