### ISSUE TITLE
Exception after running for a few hours

### ISSUE THREAD

**Issue by antongeorgiev** [build-canaries/nevergreen#204]
For bug report please fill in as many of the following details as possible:

1. how are you running?  `downloaded jar` 
2. what version? e.g. `v1.0.0`
3. what commit hash? e.g. `d7c07c1`
4. which browser are you running in? `midori 0.5.11`

Exception:
`[qtp22494844-83] ERROR nevergreen.wrap-exceptions - An unhandled exception was thrown by endpoint [/api/projects/interesting]
org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 38; Attribute "lastBuildStatus" was already specified for element "Project".
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanAttribute(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at clojure.xml$startparse_sax.invokeStatic(xml.clj:76)
        at clojure.xml$startparse_sax.invoke(xml.clj:75)
        at clojure.xml$parse.invokeStatic(xml.clj:92)
        at clojure.xml$parse.invoke(xml.clj:78)
        at clojure.xml$parse.invokeStatic(xml.clj:86)
        at clojure.xml$parse.invoke(xml.clj:78)
        at clj_cctray.parser$to_map.invokeStatic(parser.clj:13)
        at clj_cctray.parser$to_map.invoke(parser.clj:12)
        at clj_cctray.parser$get_projects.invokeStatic(parser.clj:30)
        at clj_cctray.parser$get_projects.invoke(parser.clj:25)
        at clj_cctray.core$get_projects.invokeStatic(core.clj:44)
        at clj_cctray.core$get_projects.invoke(core.clj:34)
        at nevergreen.api.projects$fetch_tray.invokeStatic(projects.clj:60)
        at nevergreen.api.projects$fetch_tray.invoke(projects.clj:51)
        at nevergreen.api.projects$fetch_interesting.invokeStatic(projects.clj:72)
        at nevergreen.api.projects$fetch_interesting.invoke(projects.clj:69)
        at nevergreen.api.projects$get_interesting.invokeStatic(projects.clj:87)
        at nevergreen.api.projects$get_interesting.invoke(projects.clj:85)
        at nevergreen.api.routes$fn__6538.invokeStatic(routes.clj:24)
        at nevergreen.api.routes$fn__6538.invoke(routes.clj:24)
        at compojure.core$wrap_response$fn__1890.invoke(core.clj:158)
        at compojure.core$pre_init$fn__1941.invoke(core.clj:328)
        at nevergreen.wrap_convert_keys$wrap_convert_keys$fn__6238.invoke(wrap_convert_keys.clj:8)
        at nevergreen.wrap_redact_sensitive$wrap_restore_sensitive$fn__6266.invoke(wrap_redact_sensitive.clj:17)
        at ring_curl.middleware$wrap_curl_logging$fn__6487.invoke(middleware.clj:18)
        at nevergreen.wrap_redact_sensitive$wrap_redact_sensitive$fn__6262.invoke(wrap_redact_sensitive.clj:11)
        at ring.middleware.json$wrap_json_body$fn__6006.invoke(json.clj:44)
        at ring.middleware.json$wrap_json_response$fn__6031.invoke(json.clj:87)
        at nevergreen.wrap_cache_control$wrap_no_cache$fn__6038.invoke(wrap_cache_control.clj:7)
        at nevergreen.wrap_cors_headers$wrap_cors_headers$fn__6245.invoke(wrap_cors_headers.clj:9)
        at nevergreen.wrap_exceptions$wrap_exceptions$fn__6255.invoke(wrap_exceptions.clj:12)
        at ring.middleware.gzip$wrap_gzip$fn__6526.invoke(gzip.clj:94)
        at compojure.core$pre_init$fn__1943$fn__1946.invoke(core.clj:335)
        at compojure.core$wrap_route_middleware$fn__1874.invoke(core.clj:127)
        at compojure.core$wrap_route_info$fn__1879.invoke(core.clj:137)
        at compojure.core$wrap_route_matches$fn__1883.invoke(core.clj:146)
        at compojure.core$routing$fn__1898.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2693)
        at clojure.core$some.invoke(core.clj:2684)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at compojure.core$routes$fn__1902.invoke(core.clj:192)
        at compojure.core$wrap_routes$fn__1953.invoke(core.clj:348)
        at compojure.core$routing$fn__1898.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2693)
        at clojure.core$some.invoke(core.clj:2684)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at compojure.core$routes$fn__1902.invoke(core.clj:192)
        at ring.adapter.jetty$proxy_handler$fn__2067.invoke(jetty.clj:25)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 1; Attribute name "lastBuildSta2000" associated with an element type "Project" must be followed by the ' = ' character.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanAttribute(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor197.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at clojure.xml$startparse_sax.invokeStatic(xml.clj:76)
        at clojure.xml$startparse_sax.invoke(xml.clj:75)
        at clojure.xml$parse.invokeStatic(xml.clj:92)
        at clojure.xml$parse.invoke(xml.clj:78)
        at clojure.xml$parse.invokeStatic(xml.clj:86)
        at clojure.xml$parse.invoke(xml.clj:78)
        at clj_cctray.parser$to_map.invokeStatic(parser.clj:13)
        at clj_cctray.parser$to_map.invoke(parser.clj:12)
        at clj_cctray.parser$get_projects.invokeStatic(parser.clj:30)
        at clj_cctray.parser$get_projects.invoke(parser.clj:25)
        at clj_cctray.core$get_projects.invokeStatic(core.clj:44)
        at clj_cctray.core$get_projects.invoke(core.clj:34)
        at nevergreen.api.projects$fetch_tray.invokeStatic(projects.clj:60)
        at nevergreen.api.projects$fetch_tray.invoke(projects.clj:51)
        at nevergreen.api.projects$fetch_interesting.invokeStatic(projects.clj:72)
        at nevergreen.api.projects$fetch_interesting.invoke(projects.clj:69)
        at nevergreen.api.projects$get_interesting.invokeStatic(projects.clj:87)
        at nevergreen.api.projects$get_interesting.invoke(projects.clj:85)
        at nevergreen.api.routes$fn__6538.invokeStatic(routes.clj:24)
        at nevergreen.api.routes$fn__6538.invoke(routes.clj:24)
        at compojure.core$wrap_response$fn__1890.invoke(core.clj:158)
        at compojure.core$pre_init$fn__1941.invoke(core.clj:328)
        at nevergreen.wrap_convert_keys$wrap_convert_keys$fn__6238.invoke(wrap_convert_keys.clj:8)
        at nevergreen.wrap_redact_sensitive$wrap_restore_sensitive$fn__6266.invoke(wrap_redact_sensitive.clj:17)
        at ring_curl.middleware$wrap_curl_logging$fn__6487.invoke(middleware.clj:18)
        at nevergreen.wrap_redact_sensitive$wrap_redact_sensitive$fn__6262.invoke(wrap_redact_sensitive.clj:11)
        at ring.middleware.json$wrap_json_body$fn__6006.invoke(json.clj:44)
        at ring.middleware.json$wrap_json_response$fn__6031.invoke(json.clj:87)
        at nevergreen.wrap_cache_control$wrap_no_cache$fn__6038.invoke(wrap_cache_control.clj:7)
        at nevergreen.wrap_cors_headers$wrap_cors_headers$fn__6245.invoke(wrap_cors_headers.clj:9)
        at nevergreen.wrap_exceptions$wrap_exceptions$fn__6255.invoke(wrap_exceptions.clj:12)
        at ring.middleware.gzip$wrap_gzip$fn__6526.invoke(gzip.clj:94)
        at compojure.core$pre_init$fn__1943$fn__1946.invoke(core.clj:335)
        at compojure.core$wrap_route_middleware$fn__1874.invoke(core.clj:127)
        at compojure.core$wrap_route_info$fn__1879.invoke(core.clj:137)
        at compojure.core$wrap_route_matches$fn__1883.invoke(core.clj:146)
        at compojure.core$routing$fn__1898.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2693)
        at clojure.core$some.invoke(core.clj:2684)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at compojure.core$routes$fn__1902.invoke(core.clj:192)
        at compojure.core$wrap_routes$fn__1953.invoke(core.clj:348)
        at compojure.core$routing$fn__1898.invoke(core.clj:185)
        at clojure.core$some.invokeStatic(core.clj:2693)
        at clojure.core$some.invoke(core.clj:2684)
        at compojure.core$routing.invokeStatic(core.clj:185)
        at compojure.core$routing.doInvoke(core.clj:182)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$apply.invoke(core.clj:652)
        at compojure.core$routes$fn__1902.invoke(core.clj:192)
        at ring.adapter.jetty$proxy_handler$fn__2067.invoke(jetty.clj:25)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
`

**Comment by GentlemanHal** [comment]
Hi @antongeorgiev, thanks for submitting this issue.

Reading the stack trace it looks like the cctray.xml file is malformed.

> Attribute "lastBuildStatus" was already specified for element "Project".

So with the details you've provided this seems more like an issue with your CI server and how it's generating the cctray.xml file.

Having said that, we should make Nevergreen more lenient when parsing, as the cctray.xml file format isn't exactly well defined. Having duplicate attributes is strange and might result in some info (such as build times) being slightly incorrect, but that is better than throwing errors back to the UI!

So we'll look into doing that, and if you could let us know shat CI server are you monitoring and provide [an anonymised] copy of the cctray.xml file, that would be ace.

Thanks!

**Comment by GentlemanHal** [comment]
I've looked into this a little more and duplicate attributes are not allowed in well formed XML.

> Well-formedness constraint: Unique Att Spec
>
> An attribute name must not appear more than once in the same start-tag or empty-element tag.
> https://www.w3.org/TR/xml/#sec-starttags

And it seems getting an XML parser to handle such a case is non trivial.

I've made a small fix so the error is handled better, but that will only really make a difference if you are monitoring multiple trays.

I'm going to close this for now, feel free to reopen if you have more info or think we should add more fixes.
