### ISSUE TITLE
Wrong credentials stop the app

### ISSUE THREAD

**Issue by bamdadd** [build-canaries/nevergreen#61]
Wrong Basicauth credentials causes the app to stop.
Possible solution could be to catch the exception and write to the console.
Below is the stacktrace.
```
 23, 2015 3:53:09 PM com.duelinmarkers.ring-request-logging invoke
INFO: Request start: :get /api/projects url=https%3A%2F%2Fgoserver%2Fgo%2Fcctray.xml&serverType=
Feb 23, 2015 3:53:10 PM com.duelinmarkers.ring-request-logging invoke
SEVERE: Unhandled throwable
clojure.lang.ExceptionInfo: clj-http: status 401 {:object {:orig-content-encoding nil, :trace-redirects ["https://goserver/go/cctray.xml"], :request-time 1131, :status 401, :headers {"WWW-Authenticate" "Basic realm=\"Restricted\"", "Connection" "close", "Content-Length" "194", "Content-Type" "text/html", "Date" "Mon, 23 Feb 2015 15:53:07 GMT
", "Server" "nginx/1.6.1"}, :body #<FilterInputStream$ff19274a clj_http.core.proxy$java.io.FilterInputStream$ff19274a@17354bff>}, :environment {client #<client$wrap_output_coercion$fn__5992 clj_http.client$wrap_output_coercion$fn__5992@3837497a>, req {:request-method :get, :url "https://goservergo/cctray.xml", :insecure? true, :timeout 3000
0, :headers {"Accept" "application/xml"}, :as :stream}, map__5876 {:orig-content-encoding nil, :trace-redirects ["https://goserver/go/cctray.xml"], :request-time 1131, :status 401, :headers {"WWW-Authenticate" "Basic realm=\"Restricted\"", "Connection" "close", "Content-Length" "194", "Content-Type" "text/html", "Date" "Mon, 23 Feb 2015 15:5
3:07 GMT", "Server" "nginx/1.6.1"}, :body #<FilterInputStream$ff19274a clj_http.core.proxy$java.io.FilterInputStream$ff19274a@17354bff>}, resp {:orig-content-encoding nil, :trace-redirects ["https://goserver/go/cctray.xml"], :request-time 1131, :status 401, :headers {"WWW-Authenticate" "Basic realm=\"Restricted\"", "Connection" "close", "Con
tent-Length" "194", "Content-Type" "text/html", "Date" "Mon, 23 Feb 2015 15:53:07 GMT", "Server" "nginx/1.6.1"}, :body #<FilterInputStream$ff19274a clj_http.core.proxy$java.io.FilterInputStream$ff19274a@17354bff>}, status 401}}
        at clj_http.client$wrap_exceptions$fn__5875.invoke(client.clj:171)
        at clj_http.client$wrap_accept$fn__6032.invoke(client.clj:522)
        at clj_http.client$wrap_accept_encoding$fn__6038.invoke(client.clj:536)
        at clj_http.client$wrap_content_type$fn__6027.invoke(client.clj:512)
        at clj_http.client$wrap_form_params$fn__6108.invoke(client.clj:683)
        at clj_http.client$wrap_nested_params$fn__6125.invoke(client.clj:707)
        at clj_http.client$wrap_method$fn__6078.invoke(client.clj:624)
        at clj_http.cookies$wrap_cookies$fn__3612.invoke(cookies.clj:122)
        at clj_http.links$wrap_links$fn__5105.invoke(links.clj:50)
        at clj_http.client$wrap_unknown_host$fn__6133.invoke(client.clj:726)
        at clj_http.client$get.doInvoke(client.clj:829)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at nevergreen.http$http_get.invoke(http.clj:7)
        at nevergreen.api$get_all_projects.invoke(api.clj:23)
        at nevergreen.app$fn__6550.invoke(app.clj:31)
        at compojure.core$make_route$fn__1389.invoke(core.clj:104)
        at compojure.core$wrap_route_middleware$fn__1385.invoke(core.clj:94)
        at compojure.core$if_route$fn__1371.invoke(core.clj:41)
        at compojure.core$if_method$fn__1363.invoke(core.clj:27)
        at compojure.core$routing$fn__1395.invoke(core.clj:118)
        at clojure.core$some.invoke(core.clj:2515)
        at compojure.core$routing.doInvoke(core.clj:118)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:626)
        at compojure.core$routes$fn__1399.invoke(core.clj:123)
        at com.duelinmarkers.ring_request_logging$wrap_param_logging$fn__6481.invoke(ring_request_logging.clj:17)
        at com.duelinmarkers.ring_request_logging$wrap_request_logging$fn__6492.invoke(ring_request_logging.clj:51)
        at nevergreen.wrap_cache_control_middleware$wrap_cache_control$fn__6535.invoke(wrap_cache_control_middleware.clj:5)
        at ring.middleware.json$wrap_json_body$fn__6512.invoke(json.clj:35)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__1543.invoke(keyword_params.clj:35)
        at ring.middleware.nested_params$wrap_nested_params$fn__1586.invoke(nested_params.clj:84)
        at ring.middleware.params$wrap_params$fn__1516.invoke(params.clj:64)
        at ring.middleware.multipart_params$wrap_multipart_params$fn__1622.invoke(multipart_params.clj:118)
        at ring.middleware.flash$wrap_flash$fn__2522.invoke(flash.clj:35)
        at ring.middleware.session$wrap_session$fn__2509.invoke(session.clj:98)
        at ring.adapter.jetty$proxy_handler$fn__2593.invoke(jetty.clj:20)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.GzipHandler.handle(GzipHandler.java:264)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:369)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)

**Comment by GentlemanHal** [comment]
Hey @bamdadd, when you say "stop the app" do you mean it completely crashes so you can't get to the tracking config page to try adding the correct credentials? 

I'd expect you to see a 500 server error message displayed where the projects should be loaded. If that is what you see then we have issue #54 to fix the user experience. 

Right now you always get a 500 error back regardless of what happens, as we don't explicitly catch any exception or check for non 200 responses coming back from the CI server.

**Comment by joejag** [comment]
Hey Bamdad, thanks for raising an issue.

When QA'ing the auth story I raised the same problem:
https://github.com/build-canaries/nevergreen/issues/38 but we decided to
punt it into #54, as Chris mentioned, since it was a general problem. Our
solution is to propagate the original error message to the client, which
should meet the needs expressed in your request.

We'll let you know when it's fixed!

Joe.

**Comment by joejag** [comment]
Hey Bamdad, the fix is up on at http://staging.nevergreen.io

**Comment by bamdadd** [comment]
Thanks guys.

**Comment by joejag** [comment]
No problem, please close the issue when you are happy it's working
