### ISSUE TITLE
Inconsistent errors and functional test failures during development

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#93]
The following error gets returned on both the tracking and monitor pages. I have a suspicion it has something to do with the source getting reloaded after changes. If I stop the `develop`script and rerun everything starts working correctly.

```
The remote server is returning "<!DOCTYPE html>
<html>
   <head>
      <title>Ring: Stacktrace</title>
      <style type="text/css">/*
         Copyright (c) 2008, Yahoo! Inc. All rights reserved.
         Code licensed under the BSD License:
         http://developer.yahoo.net/yui/license.txt
         version: 2.6.0
         */
         html{color:#000;background:#FFF;}body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,textarea,p,blockquote,th,td{margin:0;padding:0;}table{border-collapse:collapse;border-spacing:0;}fieldset,img{border:0;}address,caption,cite,code,dfn,em,strong,th,var{font-style:normal;font-weight:normal;}li{list-style:none;}caption,th{text-align:left;}h1,h2,h3,h4,h5,h6{font-size:100%;font-weight:normal;}q:before,q:after{content:'';}abbr,acronym{border:0;font-variant:normal;}sup{vertical-align:text-top;}sub{vertical-align:text-bottom;}input,textarea,select{font-family:inherit;font-size:inherit;font-weight:inherit;}input,textarea,select{*font-size:100%;}legend{color:#000;}del,ins{text-decoration:none;}
         body {
         font-family: sans-serif;
         background: #a00;
         padding: 1em;
         }
         #exception {
         background: #f2f2f2;
         color: #333;
         padding: 1em;
         }
         h1 {
         color: #800;
         font-size: 32pt;
         text-align: center;
         margin-bottom: 0.3em;
         }
         .message {
         font-size: 16pt;
         text-align: center;
         margin-bottom: 1em;
         }
         #causes h2 {
         font-size: 22pt;
         text-align: center;
         margin-bottom: 0.3em;
         }
         #causes h2 .class {
         color: #800;
         }
         #causes .message {
         font-size: 14pt;
         }
         .trace {
         width: 90%;
         margin: auto;
         }
         .trace table {
         width: 100%;
         font-size: 12pt;
         background: #dadada;
         border: 0.8em solid #dadada;
         margin-bottom: 1.5em;
         }
         .trace table tr.clojure {
         color: #222;
         }
         .trace table tr.java {
         color: #6a6a6a;
         }
         .trace td {
         padding-top: 0.4em;
         padding-bottom: 0.4em;
         }
         .trace td.method {
         padding-left: 1em;
         padding-right: 0.2em;
         text-aligh: left;
         }
         .trace td.source {
         padding-left: 0.2em;
         text-align: right;
         }
         .trace .views {
         width: 100%;
         background: #bcbcbc;
         padding: 0.5em 0;
         }
         .views .label, .views ul, .views li {
         display: inline-block;
         }
         .trace .views .label {
         padding: 0 1em;
         }
         .trace .views li {
         padding: 0 2em;
         cursor: pointer;
         }
      </style>
   </head>
   <body>
      <div id="exception">
         <h1>java.lang.UnsupportedOperationException</h1>
         <div class="message">count not supported on this type: HttpInput</div>
         <div class="trace">
            <table>
               <tbody>
                  <tr class="java">
                     <td class="source">RT.java:556</td>
                     <td class="method">clojure.lang.RT.countFrom</td>
                  </tr>
                  <tr class="java">
                     <td class="source">RT.java:530</td>
                     <td class="method">clojure.lang.RT.count</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">projects.clj:38</td>
                     <td class="method">nevergreen.api.projects/get-interesting</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">routes.clj:19</td>
                     <td class="method">nevergreen.api.routes/fn</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:113</td>
                     <td class="method">compojure.core/make-route[fn]</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:242</td>
                     <td class="method">compojure.core/pre-init[fn]</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:102</td>
                     <td class="method">compojure.core/wrap-route-middleware[fn]</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:41</td>
                     <td class="method">compojure.core/if-route[fn]</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:27</td>
                     <td class="method">compojure.core/if-method[fn]</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:127</td>
                     <td class="method">compojure.core/routing[fn]</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:2515</td>
                     <td class="method">clojure.core/some</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:127</td>
                     <td class="method">compojure.core/routing</td>
                  </tr>
                  <tr class="java">
                     <td class="source">RestFn.java:139</td>
                     <td class="method">clojure.lang.RestFn.applyTo</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:626</td>
                     <td class="method">clojure.core/apply</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:132</td>
                     <td class="method">compojure.core/routes[fn]</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:250</td>
                     <td class="method">compojure.core/wrap-routes[fn]</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:127</td>
                     <td class="method">compojure.core/routing[fn]</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:2515</td>
                     <td class="method">clojure.core/some</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:127</td>
                     <td class="method">compojure.core/routing</td>
                  </tr>
                  <tr class="java">
                     <td class="source">RestFn.java:139</td>
                     <td class="method">clojure.lang.RestFn.applyTo</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:626</td>
                     <td class="method">clojure.core/apply</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">core.clj:132</td>
                     <td class="method">compojure.core/routes[fn]</td>
                  </tr>
                  <tr class="java">
                     <td class="source">Var.java:379</td>
                     <td class="method">clojure.lang.Var.invoke</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">reload.clj:22</td>
                     <td class="method">ring.middleware.reload/wrap-reload[fn]</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">stacktrace.clj:23</td>
                     <td class="method">ring.middleware.stacktrace/wrap-stacktrace-log[fn]</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">stacktrace.clj:86</td>
                     <td class="method">ring.middleware.stacktrace/wrap-stacktrace-web[fn]</td>
                  </tr>
                  <tr class="clojure">
                     <td class="source">jetty.clj:20</td>
                     <td class="method">ring.adapter.jetty/proxy-handler[fn]</td>
                  </tr>
                  <tr class="java">
                     <td class="source">(Unknown Source)</td>
                     <td class="method">ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle</td>
                  </tr>
                  <tr class="java">
                     <td class="source">HandlerWrapper.java:116</td>
                     <td class="method">org.eclipse.jetty.server.handler.HandlerWrapper.handle</td>
                  </tr>
                  <tr class="java">
                     <td class="source">Server.java:369</td>
                     <td class="method">org.eclipse.jetty.server.Server.handle</td>
                  </tr>
                  <tr class="java">
                     <td class="source">AbstractHttpConnection.java:486</td>
                     <td class="method">org.eclipse.jetty.server.AbstractHttpConnection.handleRequest</td>
                  </tr>
                  <tr class="java">
                     <td class="source">AbstractHttpConnection.java:944</td>
                     <td class="method">org.eclipse.jetty.server.AbstractHttpConnection.content</td>
                  </tr>
                  <tr class="java">
                     <td class="source">AbstractHttpConnection.java:1005</td>
                     <td class="method">org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content</td>
                  </tr>
                  <tr class="java">
                     <td class="source">HttpParser.java:865</td>
                     <td class="method">org.eclipse.jetty.http.HttpParser.parseNext</td>
                  </tr>
                  <tr class="java">
                     <td class="source">HttpParser.java:240</td>
                     <td class="method">org.eclipse.jetty.http.HttpParser.parseAvailable</td>
                  </tr>
                  <tr class="java">
                     <td class="source">AsyncHttpConnection.java:82</td>
                     <td class="method">org.eclipse.jetty.server.AsyncHttpConnection.handle</td>
                  </tr>
                  <tr class="java">
                     <td class="source">SelectChannelEndPoint.java:668</td>
                     <td class="method">org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle</td>
                  </tr>
                  <tr class="java">
                     <td class="source">SelectChannelEndPoint.java:52</td>
                     <td class="method">org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run</td>
                  </tr>
                  <tr class="java">
                     <td class="source">QueuedThreadPool.java:608</td>
                     <td class="method">org.eclipse.jetty.util.thread.QueuedThreadPool.runJob</td>
                  </tr>
                  <tr class="java">
                     <td class="source">QueuedThreadPool.java:543</td>
                     <td class="method">org.eclipse.jetty.util.thread.QueuedThreadPool$3.run</td>
                  </tr>
                  <tr class="java">
                     <td class="source">Thread.java:745</td>
                     <td class="method">java.lang.Thread.run</td>
                  </tr>
               </tbody>
            </table>
         </div>
      </div>
   </body>
</html>"
```

**Comment by GentlemanHal** [comment]
Have just seen this error:

```
java.lang.IllegalArgumentException: Don't know how to create ISeq from: ring.util.response$charset$fn__103
        at clojure.lang.RT.seqFrom(RT.java:528)
        at clojure.lang.RT.seq(RT.java:509)
        at clojure.lang.RT.cons(RT.java:648)
        at clojure.core$cons__4102.invoke(core.clj:29)
        at clojure.core$list_STAR_.invoke(core.clj:619)
        at clojure.core$apply.invoke(core.clj:632)
        at ring.util.response$update_header$fn__99.invoke(response.clj:181)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:632)
        at clojure.core$update_in.doInvoke(core.clj:5923)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invoke(core.clj:636)
        at clojure.core$update_in.doInvoke(core.clj:5922)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at ring.util.response$update_header.doInvoke(response.clj:181)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at ring.util.response$charset.invoke(response.clj:188)
        at ring.middleware.default_charset$add_charset.invoke(default_charset.clj:17)
        at ring.middleware.default_charset$wrap_default_charset$fn__6710.invoke(default_charset.clj:27)
        at ring.middleware.not_modified$wrap_not_modified$fn__6683.invoke(not_modified.clj:52)
        at ring.middleware.x_headers$wrap_xss_protection$fn__6192.invoke(x_headers.clj:71)
        at ring.middleware.x_headers$wrap_frame_options$fn__6180.invoke(x_headers.clj:38)
        at ring.middleware.x_headers$wrap_content_type_options$fn__6186.invoke(x_headers.clj:53)
        at nevergreen.wrap_cache_control$wrap_cache_control$fn__5653.invoke(wrap_cache_control.clj:5)
        at nevergreen.wrap_exceptions$wrap_exceptions$fn__5861.invoke(wrap_exceptions.clj:29)
        at ring.middleware.gzip$wrap_gzip$fn__6118.invoke(gzip.clj:94)
        at compojure.core$pre_init$fn__1524$fn__1525.invoke(core.clj:259)
        at compojure.core$wrap_route_middleware$fn__1479.invoke(core.clj:117)
        at compojure.core$if_route$fn__1455.invoke(core.clj:41)
        at compojure.core$if_method$fn__1447.invoke(core.clj:27)
        at compojure.core$routing$fn__1490.invoke(core.clj:144)
        at clojure.core$some.invoke(core.clj:2570)
        at compojure.core$routing.doInvoke(core.clj:144)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:632)
        at compojure.core$routes$fn__1494.invoke(core.clj:149)
        at compojure.core$wrap_routes$fn__1530.invoke(core.clj:267)
        at compojure.core$routing$fn__1490.invoke(core.clj:144)
        at clojure.core$some.invoke(core.clj:2570)
        at compojure.core$routing.doInvoke(core.clj:144)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:632)
        at compojure.core$routes$fn__1494.invoke(core.clj:149)
        at clojure.lang.Var.invoke(Var.java:379)
        at ring.middleware.reload$wrap_reload$fn__1225.invoke(reload.clj:22)
        at ring.middleware.stacktrace$wrap_stacktrace_log$fn__657.invoke(stacktrace.clj:23)
        at ring.middleware.stacktrace$wrap_stacktrace_web$fn__719.invoke(stacktrace.clj:86)
        at ring.adapter.jetty$proxy_handler$fn__1597.invoke(jetty.clj:24)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by GentlemanHal** [comment]
Have now seen this error:

```clojure
java.lang.NoClassDefFoundError: ring/middleware/nested_params$nest_params$fn__6522
        at ring.middleware.nested_params$nest_params.invoke(nested_params.clj:50)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:632)
        at clojure.core$update_in.doInvoke(core.clj:5923)
        at clojure.lang.RestFn.invoke(RestFn.java:467)
        at ring.middleware.nested_params$nested_params_request.doInvoke(nested_params.clj:63)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at ring.middleware.nested_params$wrap_nested_params$fn__6531.invoke(nested_params.clj:84)
        at ring.middleware.multipart_params$wrap_multipart_params$fn__6646.invoke(multipart_params.clj:117)
        at ring.middleware.params$wrap_params$fn__6666.invoke(params.clj:64)
        at ring.middleware.cookies$wrap_cookies$fn__6364.invoke(cookies.clj:161)
        at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__6772.invoke(absolute_redirects.clj:36)
        at ring.middleware.resource$wrap_resource$fn__6690.invoke(resource.clj:28)
        at ring.middleware.content_type$wrap_content_type$fn__6741.invoke(content_type.clj:30)
        at ring.middleware.default_charset$wrap_default_charset$fn__6755.invoke(default_charset.clj:26)
        at ring.middleware.not_modified$wrap_not_modified$fn__6728.invoke(not_modified.clj:52)
        at ring.middleware.x_headers$wrap_xss_protection$fn__6237.invoke(x_headers.clj:71)
        at ring.middleware.x_headers$wrap_frame_options$fn__6225.invoke(x_headers.clj:38)
        at ring.middleware.x_headers$wrap_content_type_options$fn__6231.invoke(x_headers.clj:53)
        at nevergreen.wrap_cache_control$wrap_cache_control$fn__5696.invoke(wrap_cache_control.clj:5)
        at nevergreen.wrap_exceptions$wrap_exceptions$fn__5904.invoke(wrap_exceptions.clj:29)
        at ring.middleware.gzip$wrap_gzip$fn__6161.invoke(gzip.clj:94)
        at compojure.core$pre_init$fn__1524$fn__1525.invoke(core.clj:259)
        at compojure.core$wrap_route_middleware$fn__1479.invoke(core.clj:117)
        at compojure.core$if_route$fn__1455.invoke(core.clj:41)
        at compojure.core$if_method$fn__1447.invoke(core.clj:27)
        at compojure.core$routing$fn__1490.invoke(core.clj:144)
        at clojure.core$some.invoke(core.clj:2570)
        at compojure.core$routing.doInvoke(core.clj:144)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:632)
        at compojure.core$routes$fn__1494.invoke(core.clj:149)
        at compojure.core$wrap_routes$fn__1530.invoke(core.clj:267)
        at compojure.core$routing$fn__1490.invoke(core.clj:144)
        at clojure.core$some.invoke(core.clj:2570)
        at compojure.core$routing.doInvoke(core.clj:144)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:632)
        at compojure.core$routes$fn__1494.invoke(core.clj:149)
        at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: ring.middleware.nested_params$nest_params$fn__6522
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 46 more
Thu Jan 21 17:19:25 GMT 2016 [worker-2] ERROR - GET /favicon.ico
java.lang.NoClassDefFoundError: ring/middleware/nested_params$nest_params$fn__6522
        at ring.middleware.nested_params$nest_params.invoke(nested_params.clj:50)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:632)
        at clojure.core$update_in.doInvoke(core.clj:5923)
        at clojure.lang.RestFn.invoke(RestFn.java:467)
        at ring.middleware.nested_params$nested_params_request.doInvoke(nested_params.clj:63)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at ring.middleware.nested_params$wrap_nested_params$fn__6531.invoke(nested_params.clj:84)
        at ring.middleware.multipart_params$wrap_multipart_params$fn__6646.invoke(multipart_params.clj:117)
        at ring.middleware.params$wrap_params$fn__6666.invoke(params.clj:64)
        at ring.middleware.cookies$wrap_cookies$fn__6364.invoke(cookies.clj:161)
        at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__6772.invoke(absolute_redirects.clj:36)
        at ring.middleware.resource$wrap_resource$fn__6690.invoke(resource.clj:28)
        at ring.middleware.content_type$wrap_content_type$fn__6741.invoke(content_type.clj:30)
        at ring.middleware.default_charset$wrap_default_charset$fn__6755.invoke(default_charset.clj:26)
        at ring.middleware.not_modified$wrap_not_modified$fn__6728.invoke(not_modified.clj:52)
        at ring.middleware.x_headers$wrap_xss_protection$fn__6237.invoke(x_headers.clj:71)
        at ring.middleware.x_headers$wrap_frame_options$fn__6225.invoke(x_headers.clj:38)
        at ring.middleware.x_headers$wrap_content_type_options$fn__6231.invoke(x_headers.clj:53)
        at nevergreen.wrap_cache_control$wrap_cache_control$fn__5696.invoke(wrap_cache_control.clj:5)
        at nevergreen.wrap_exceptions$wrap_exceptions$fn__5904.invoke(wrap_exceptions.clj:29)
        at ring.middleware.gzip$wrap_gzip$fn__6161.invoke(gzip.clj:94)
        at compojure.core$pre_init$fn__1524$fn__1525.invoke(core.clj:259)
        at compojure.core$wrap_route_middleware$fn__1479.invoke(core.clj:117)
        at compojure.core$if_route$fn__1455.invoke(core.clj:41)
        at compojure.core$if_method$fn__1447.invoke(core.clj:27)
        at compojure.core$routing$fn__1490.invoke(core.clj:144)
        at clojure.core$some.invoke(core.clj:2570)
        at compojure.core$routing.doInvoke(core.clj:144)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:632)
        at compojure.core$routes$fn__1494.invoke(core.clj:149)
        at compojure.core$wrap_routes$fn__1530.invoke(core.clj:267)
        at compojure.core$routing$fn__1490.invoke(core.clj:144)
        at clojure.core$some.invoke(core.clj:2570)
        at compojure.core$routing.doInvoke(core.clj:144)
        at clojure.lang.RestFn.applyTo(RestFn.java:139)
        at clojure.core$apply.invoke(core.clj:632)
        at compojure.core$routes$fn__1494.invoke(core.clj:149)
        at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by GentlemanHal** [comment]
These might not all be related to the same underlying problem but they are all intermittent errors that killing and restarting the develop script fixes.

**Comment by GentlemanHal** [comment]
http://seleniumhq.org/exceptions/stale_element_reference.html

**Comment by GentlemanHal** [comment]
Since updating to use Redux (#142) I haven't seen the state reference issue, so this may now be fixed...

**Comment by GentlemanHal** [comment]
I've ran the tests many times over the last few weeks without any flakey failures, so I'm happy to close this issue for now. We can always re-open if we start noticing flakey failures again.
